### ISSUE TITLE
crap

### ISSUE THREAD

**Issue by KrashKrash** [Ghahuri/Blockchain-Unconfirmed-Transaction-Script.#3]
this is bullshit. i have still not got my BTC. lol.

**Comment by Nkere247** [comment]
the main fill was removed earlier. and its now a paid service . id send you
a download link once you make payment.

**Comment by KrashKrash** [comment]
lol. dude....just stop alrdy

**Comment by Nkere247** [comment]
What do you mean? I've told you all you need to know already. If you feel
it's not working for you, fine, I've got other people to attend to.
